app = "aiostreams-qbkjgg"  # Change this to match your Fly.io app name

primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  AIOS_CONFIG__FRONTEND_ENABLED = "true"
  AIOS_CONFIG__FRONTEND_AUTH = ""
  AIOS_CONFIG__SCRAPER_TIMEOUT = "15"
  AIOS_CONFIG__SCRAPER_TEMPLATES = "templates"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [
    { handlers = ["http"], port = 80 },
    { handlers = ["tls", "http"], port = 443 }
  ]
  auto_start = true
  auto_stop = true
